// Builds the morning digest posted to #pending-escalations-summariser.
// Input: open-escalation records accumulated in KV by the nudger, each shaped
// { threadTs, permalink, blocker, critical, one_line, pocs }.
// Presentation is leadership-facing: clean sections, grouped categories, counts.

const { BLOCKERS, CRITICAL_SIGNALS } = require("./poc-map");
const { tagAll } = require("./nudge");

// Group the fine-grained blocker keys into leadership-friendly categories.
const CATEGORY_OF = {
  replacement_not_assigned: "Pending on Replacement",
  replacement_delivery_pending: "Pending on Replacement",
  spare_not_sent: "Pending on Spare Part",
  revisit_not_aligned: "Pending on Revisit",
  revisit_eta_pending: "Pending on Revisit",
  rca_not_closed: "Pending on Tech / RCA",
  reverse_pickup_pending: "Pending on Reverse Pickup",
  delivery_delay: "Pending on Delivery",
  install_quality: "Pending on Install Quality (PX)",
  awaiting_diagnosis: "Awaiting Diagnosis / Next Step",
};
// Display order for categories.
const CATEGORY_ORDER = [
  "Pending on Tech / RCA",
  "Pending on Replacement",
  "Pending on Spare Part",
  "Pending on Revisit",
  "Pending on Reverse Pickup",
  "Pending on Delivery",
  "Pending on Install Quality (PX)",
  "Awaiting Diagnosis / Next Step",
];

function buildDigest(records, { channelName }) {
  const open = Array.isArray(records) ? records : [];
  const critical = open.filter((r) => r.critical && r.critical.length);
  const normal = open.filter((r) => !(r.critical && r.critical.length));

  const today = new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: "Asia/Kolkata" });

  // Bucket normal escalations by leadership category.
  const byCat = {};
  for (const r of normal) {
    const cat = CATEGORY_OF[r.blocker] || "Awaiting Diagnosis / Next Step";
    (byCat[cat] = byCat[cat] || []).push(r);
  }
  const cats = CATEGORY_ORDER.filter((c) => byCat[c] && byCat[c].length);

  const L = [];
  L.push(`*NATIVE LOCKS — PENDING ESCALATIONS*`);
  L.push(`_${today} · source #${channelName}_`);
  L.push("");

  // Snapshot line.
  const summaryBits = [`*${open.length}* open`, `:rotating_light: *${critical.length}* critical`];
  for (const c of cats) summaryBits.push(`${c.replace("Pending on ", "")}: *${byCat[c].length}*`);
  L.push(summaryBits.join("  ·  "));
  L.push("――――――――――――――――――――");

  // --- Critical section ---
  L.push(`:rotating_light: *CRITICAL — ${critical.length}*`);
  if (!critical.length) {
    L.push("_None pending._");
  } else {
    critical.forEach((r, i) => {
      const key = r.critical[0];
      const label = (CRITICAL_SIGNALS[key] && CRITICAL_SIGNALS[key].label) || key;
      L.push(`${i + 1}. *${label}*`);
      L.push(`     ${r.one_line || "—"}`);
      L.push(`     Blocked on ${tagAll(r.pocs || [])} · <${r.permalink}|view thread>`);
    });
  }
  L.push("――――――――――――――――――――");

  // --- Product issues by category ---
  L.push(`:wrench: *PRODUCT ISSUES — ${normal.length}*`);
  if (!normal.length) L.push("_None pending._");
  for (const cat of cats) {
    const group = byCat[cat];
    L.push("");
    L.push(`*${cat}  ·  ${group.length}*`);
    group.forEach((r) => {
      L.push(`• ${r.one_line || "(no summary)"}`);
      if (r.last_activity) L.push(`     _latest: ${r.last_activity}_`);
      L.push(`     → ${tagAll(r.pocs || [])} · <${r.permalink}|view thread>`);
    });
  }

  L.push("");
  L.push(`_Auto-generated by Native Locks Escalations bot. Each item is being nudged in-thread until resolved._`);

  return L.join("\n");
}

module.exports = { buildDigest };
